apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../crds
- ../cluster-rbac/application-controller
- ../base/config
- ../base/application-controller
- ../base/applicationset-controller
- ../base/repo-server
- ../base/redis
images:
- name: quay.io/argoproj/argocd
  newName: us-central1-docker.pkg.dev/maralder-anthos-dev/argocd-images/argocd
  newTag: latest
